/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-2',
  aws_cloud_logic_custom: [
    {
      name: 'mainapis',
      endpoint: 'https://xqu9eyuvuh.execute-api.eu-west-2.amazonaws.com/dev',
      region: 'eu-west-2',
    },
    {
      name: 'apic60289d2',
      endpoint: 'https://mwb0eh2zb2.execute-api.eu-west-2.amazonaws.com/dev',
      region: 'eu-west-2',
    },
  ],
  aws_cognito_identity_pool_id:
    'eu-west-2:59d84fe5-bb9c-4655-aca1-48eb48da5ecf',
  aws_cognito_region: 'eu-west-2',
  aws_user_pools_id: 'eu-west-2_yGeBpsvUg',
  aws_user_pools_web_client_id: '7t59v1rpfetgcl41mh3agld0m5',
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
};

export default awsmobile;
