export default {
  moneyReceived: false,
  referrals: {
    sentReferrals: [],
    pendingReferrals: [],
  },
  giftCards: {
    pending: [],
    accepted: [],
  },
  timer: {
    id1: '',
    id2: '',
    id3: '',
    id4: '',
  },
  currencies: {
    USD: { decimals: 2, displaySymbol: 'USD', totalSymbol: 'USD' },
    CAD: { decimals: 2, displaySymbol: 'CAD', totalSymbol: 'CAD' },
    AUD: { decimals: 2, displaySymbol: 'AUD', totalSymbol: 'AUD' },
    CHF: { decimals: 2, displaySymbol: 'CHF', totalSymbol: 'CHF' },
    EUR: { decimals: 2, displaySymbol: 'EUR', totalSymbol: 'EUR' },
    GBP: { decimals: 2, displaySymbol: 'GBP', totalSymbol: 'GBP' },
    JPY: { decimals: 2, displaySymbol: 'JPY', totalSymbol: 'JPY' },
    NZD: { decimals: 2, displaySymbol: 'NZD', totalSymbol: 'NZD' },
    NOK: { decimals: 2, displaySymbol: 'NOK', totalSymbol: 'NOK' },
    SEK: { decimals: 2, displaySymbol: 'SEK', totalSymbol: 'SEK' },
    Gold: { decimals: 4, displaySymbol: 'Oz', totalSymbol: 'Oz of Gold' },
    GoldBritannia: { decimals: 4, displaySymbol: 'Oz', totalSymbol: 'Oz of Gold' },
    GoldSovereign: { decimals: 4, displaySymbol: 'Oz', totalSymbol: 'Oz of Gold' },
    SilverBritannia: { decimals: 4, displaySymbol: 'Oz', totalSymbol: 'Oz of Silver' },
    Silver: { decimals: 4, displaySymbol: 'Oz', totalSymbol: 'Oz of Silver' },
    Platinum: { decimals: 4, displaySymbol: 'Oz', totalSymbol: 'Oz of Platinum' },
    Oil: { decimals: 4, displaySymbol: 'Barrels', totalSymbol: 'Barrels of Oil' },
    FTSE: { decimals: 4, displaySymbol: 'Shares', totalSymbol: 'FTSE Shares' },
    'S&P': { decimals: 4, displaySymbol: 'Shares', totalSymbol: 'S&P Shares' },
    EURSTOXX: { decimals: 4, displaySymbol: 'Shares', totalSymbol: 'EURSTX Shares' },
    BTC: { decimals: 5, displaySymbol: 'BTC', totalSymbol: 'BTC' },
    ETH: { decimals: 4, displaySymbol: 'ETH', totalSymbol: 'ETH' },
    XRP: { decimals: 2, displaySymbol: 'XRP', totalSymbol: 'XRP' },
    LTC: { decimals: 4, displaySymbol: 'LTC', totalSymbol: 'LTC' },
  },
  contractValues: {
    flatFeeValues: '',
    purchaseWithCreditCardFeeValues: '',
    purchaseWithCryptoFeeValues: '',
    purchaseWithEurCreditCardFeeValues: '',
    storageFeeValues: '',
    priceModifiers: [],
  },
  user: {
    id: '',
    email: '',
    admin: false,
    superAdmin: false,
    pin: '',
    transactionFeeValues: [],
    freeTransactionsPerMonth: 0,
    referrerAddress: '',
    exchangeFeePercentage: 0.0,
    transactionsCount: 0,
    password: '',
    firstName: '',
    lastName: '',
    usedReferralCode: '',
    isSuperUser: false,
    walletAddress: '',
    balance: '',
    nonce: '',
    USDBalance: 0,
    CADBalance: 0,
    AUDBalance: 0,
    CHFBalance: 0,
    EURBalance: 0,
    GBPBalance: 0,
    JPYBalance: 0,
    NOKBalance: 0,
    NZDBalance: 0,
    SEKBalance: 0,
    GoldBalance: 0,
    GoldBritanniaBalance: 0,
    GoldSovereignBalance: 0,
    SilverBritanniaBalance: 0,
    SilverBalance: 0,
    PlatinumBalance: 0,
    OilBalance: 0,
    FTSEBalance: 0,
    'S&PBalance': 0,
    EURSTOXXBalance: 0,
    BTCBalance: 0,
    ETHBalance: 0,
    XRPBalance: 0,
    LTCBalance: 0,
    USDConvertedBalance: '',
    CADConvertedBalance: '',
    AUDConvertedBalance: '',
    CHFConvertedBalance: '',
    EURConvertedBalance: '',
    GBPConvertedBalance: '',
    JPYConvertedBalance: '',
    NOKConvertedBalance: '',
    NZDConvertedBalance: '',
    SEKConvertedBalance: '',
    GoldConvertedBalance: '',
    GoldBritanniaConvertedBalance: '',
    GoldSovereignConvertedBalance: '',
    SilverBritanniaConvertedBalance: '',
    SilverConvertedBalance: '',
    PlatinumConvertedBalance: '',
    OilConvertedBalance: '',
    FTSEConvertedBalance: '',
    'S&PConvertedBalance': '',
    EURSTOXXConvertedBalance: '',
    BTCConvertedBalance: '',
    ETHConvertedBalance: '',
    XRPConvertedBalance: '',
    LTCConvertedBalance: '',
    availableReferrals: 0,
    referralCode: '',
    currency: { symbol: 'USD' },
    locales: {},
    userConfirmed: false,
    coords: {
      latitude: 31.907185109980887,
      longitude: -104.11959266290069,
      latitudeDelta: 51.43172567808486,
      longitudeDelta: 66.95441152900457,
    },
    customerId: '',
    encryptedKey: '',
    hashKey: {},
    sources: [],
    firstTime: false,
    kyc: { phone: '', status: null },
    business: {
      name: 'Loading',
      description: 'Loading...',
      streetAddress: '',
      latitude: 0,
      longitude: 0,
      imageUrl: '',
      phone: '',
      websiteUrl: '',
      categoryId: null,
    },
  },
  purchase: {
    amount: '',
    plan: {},
    source: {},
    type: '',
    currency: '',
  },
  transfer: {
    name: '',
    amount: '',
    toAddress: '',
    memo: '',
    type: '',
    toSymbol: '',
    fromSymbol: '',
    toEmail: '',
  },
  businesses: [],
  transactions: [],
  promotions: [],
  plans: [],
  cart: [],
  notifications: [],
  friends: [],
  communityTransactions: [],
  bankAccounts: [],
}
